
- hosts: front_ends
  become: true
  tasks:
      - name: Pull front git directory
        git:
            repo: https://github.com/skamal10/TwitterApp.git
            dest: /var/www/html/cse356

      - name: Restart NginX
        shell: systemctl restart nginx
      


# To run ansible-playbook -s auto_pull.yml -u ubuntu 
