---
- hosts: front_ends
  become: true
  tasks:
      - name: start app
        shell: pm2 start /var/www/html/cse356/bin/www --watch
      
      - name: Restart NginX
        shell: systemctl restart nginx




 # To run ansible-playbook -s restart_pm2.yml -u ubuntu
